import html
import logging
import os
import tempfile
import zoneinfo
from datetime import time, timedelta

from telegram import Bot, Message, Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.constants import ParseMode
from telegram.ext import (
    Application,
    ApplicationBuilder,
    CallbackQueryHandler,
    CommandHandler,
    ContextTypes,
    ConversationHandler,
    MessageHandler,
    PicklePersistence,
    TypeHandler,
    filters,
)

from config import settings
from services.formatter import format_entry
from services.notion import save_entry
from services.summary import generate_daily_summary, generate_weekly_report
from services.whisper import transcribe

logging.basicConfig(
    format="%(asctime)s [%(levelname)s] %(message)s",
    level=logging.INFO,
)

# httpx logs every request at INFO, and the Telegram API puts the bot token in
# the path: "POST https://api.telegram.org/bot<TOKEN>/getUpdates". Polling runs
# every few seconds, so at INFO the token is written to the journal thousands of
# times a day, where anyone who can read the unit's log can lift it — including
# the deploy account, whose whole point is that it cannot reach the credentials.
# WARNING keeps the failures and drops the successful-request line that carries
# the secret.
logging.getLogger("httpx").setLevel(logging.WARNING)

logger = logging.getLogger(__name__)

PREVIEW, EDIT_TITLE, EDIT_TEXT, EDIT_TAGS = range(4)

# `JobQueue.run_daily` numbers weekdays 0-6 as Sunday-Saturday, not Monday-Sunday.
# The mapping was flipped in python-telegram-bot 20.0, and the old reading of it is
# why the weekly report used to arrive on Saturday. Never pass a bare number here.
SUNDAY = 0

DAILY_SUMMARY_JOB = "daily_summary"
WEEKLY_REPORT_JOB = "weekly_report"

# Everything in user_data that belongs to one draft. Cleared together, so a draft can
# never survive half-way and leave message ids pointing at a preview that is gone.
DRAFT_KEYS = (
    "pending",
    "title_msg_id",
    "text_msg_id",
    "tags_msg_id",
    "buttons_msg_id",
    "edit_prompt_msg_id",
    "editing_state",
    "saving",
)

# Message ids of previews that were saved, so a press arriving from a client whose view
# has not caught up is answered honestly instead of being called a lost draft. Only a
# handful are worth keeping.
SAVED_BUTTONS_KEY = "saved_buttons"
SAVED_BUTTONS_REMEMBERED = 10

# Long enough that no realistic dictate-and-edit session gets cut off, short enough
# that a preview abandoned in the morning is not still live when the 21:00 jobs run.
PREVIEW_TIMEOUT = timedelta(minutes=30)

# Drafts live in user_data, which is in-memory, and `make deploy` restarts the bot on
# every push. Without somewhere to put them a preview from a minute earlier comes back
# with working buttons and nothing behind them. The file holds a draft, not a secret,
# but it is local runtime state and is gitignored.
STATE_FILE_NAME = "bot_state.pickle"
CONVERSATION_NAME = "preview_flow"

WELCOME_TEXT = """👋 Welcome to Noter!

I turn your voice messages into structured diary entries in Notion.

Send me a voice message and I'll:
• Transcribe it
• Format it into a title and clean text
• Let you review and edit before saving
• Save it to your Notion journal

Every day at 21:00 I'll send you a summary of the day.

Type /help to see detailed instructions."""

HELP_TEXT = """<b>How to use Noter</b>

1. Send a voice message — speak naturally, I'll handle the rest
2. Review the preview:
   • <b>Title</b> — short heading generated by AI
   • <b>Text</b> — cleaned up transcription
   • <b>Tags</b> — auto-extracted + <code>Daily</code> (always added)
3. Edit anything using the buttons
4. Press <b>✓ Save</b> to send to Notion

<b>Editing</b>
<b>✎ Title</b> — send a new title
<b>✎ Text</b> — send a new text
<b>✎ Tags</b> — send tags separated by commas: <code>sport, health, work</code>
<b>/cancel</b> — throw the current draft away, same as the ✕ Cancel button

<b>Daily summary</b>
Every day at 21:00 I send a summary of all entries recorded that day. If there are none, I'll send a friendly nudge instead."""

# Shown to the user when something breaks. They say which step failed and what to do
# next; the exception itself belongs in the log, where it is readable and where it
# cannot end up quoting a third-party response body back into the chat.
DOWNLOAD_FAILED = "I couldn't download that voice message. Send it again and I'll retry."
TRANSCRIBE_FAILED = "I couldn't transcribe that voice message. Send it again and I'll retry."
FORMAT_FAILED = "I transcribed it but couldn't turn it into an entry. Send the voice message again."
PREVIEW_FAILED = "I couldn't show the preview for that entry. Send the voice message again."
NOTION_FAILED = "I couldn't reach Notion, so nothing was saved. Press Save to try again."

DRAFT_REPLACED = "✕ Draft discarded — a newer recording replaced it."
DRAFT_CANCELLED = "✕ Draft discarded."
DRAFT_TIMED_OUT = (
    "✕ Draft discarded — the preview went unanswered for "
    f"{int(PREVIEW_TIMEOUT.total_seconds() // 60)} minutes."
)
NOTHING_TO_CANCEL = "There is no draft open right now."
DRAFT_GONE = "That draft is no longer available. Send a new voice message and I'll start over."
SOMETHING_BROKE = "Something went wrong on my side. It is in the log — please try that again."
SAVE_IN_FLIGHT = "Still saving — one moment."
ALREADY_SAVED = "Already saved."
SAVING_NOTICE = "Saving to Notion..."

TITLE_TEMPLATE = "<b>{title}</b>"
TAG_TEMPLATE = "<code>{tag}</code>"
DAILY_SUMMARY_TEMPLATE = "<b>Daily summary</b>\n\n{summary}"
WEEKLY_REPORT_TEMPLATE = "<b>Weekly highlights</b>\n\n{report}"


def render(template: str, **values: object) -> str:
    """Builds a message body for ParseMode.HTML, escaping every interpolated value.

    Titles and tags come from gpt-4o-mini or from whatever the user typed, and the
    summaries are written entirely by the model. Any of them can contain characters
    that mean something to Telegram's parser, and an unbalanced one rejects the whole
    message. Assembling message bodies here — and nowhere else — is what keeps that
    from being reintroduced the next time a message is added to this bot.
    """
    escaped = {key: html.escape(str(value), quote=False) for key, value in values.items()}
    return template.format(**escaped)


def _title_body(title: str) -> str:
    return render(TITLE_TEMPLATE, title=title)


async def reply_html(message: Message, body: str, **kwargs: object) -> Message:
    """Replies with a body produced by render(); the parse mode is not a call-site choice."""
    return await message.reply_text(body, parse_mode=ParseMode.HTML, **kwargs)


async def send_html(bot: Bot, chat_id: int, body: str, **kwargs: object) -> Message:
    return await bot.send_message(chat_id=chat_id, text=body, parse_mode=ParseMode.HTML, **kwargs)


async def edit_html(bot: Bot, chat_id: int, message_id: int, body: str, **kwargs: object) -> None:
    await bot.edit_message_text(
        chat_id=chat_id,
        message_id=message_id,
        text=body,
        parse_mode=ParseMode.HTML,
        **kwargs,
    )


def _tags_line(tags: list[str]) -> str:
    all_tags = ["Daily"] + [t for t in tags if t != "Daily"]
    return " ".join(render(TAG_TEMPLATE, tag=t) for t in all_tags)


def _clear_draft(context: ContextTypes.DEFAULT_TYPE) -> dict:
    """Forgets the current draft and returns what was stored, message ids included."""
    return {key: context.user_data.pop(key, None) for key in DRAFT_KEYS}


async def _retire_preview(bot: Bot, chat_id: int, draft: dict, notice: str) -> bool:
    """Takes the buttons off a preview that is no longer backed by a draft.

    Editing the text of the buttons message and passing no markup is what removes the
    keyboard, so the dead buttons disappear rather than sitting there doing nothing.
    """
    buttons_msg_id = draft.get("buttons_msg_id")
    if buttons_msg_id is None:
        return False
    try:
        await edit_html(bot, chat_id, buttons_msg_id, notice, reply_markup=None)
    except Exception:
        logger.warning("Could not retire preview message %s", buttons_msg_id, exc_info=True)
    return True


async def _delete_messages(bot: Bot, chat_id: int, message_ids) -> None:
    for message_id in message_ids:
        if message_id is None:
            continue
        try:
            await bot.delete_message(chat_id, message_id)
        except Exception:
            logger.warning("Could not delete message %s", message_id, exc_info=True)


def _remember_saved(context: ContextTypes.DEFAULT_TYPE, buttons_msg_id: int | None) -> None:
    if buttons_msg_id is None:
        return
    saved = context.user_data.setdefault(SAVED_BUTTONS_KEY, [])
    saved.append(buttons_msg_id)
    del saved[:-SAVED_BUTTONS_REMEMBERED]


async def _draft_missing(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    """Deals with an action aimed at a draft that is no longer there.

    A preview that outlived its draft is the one failure the user cannot see: the
    button stays live and pressing it used to raise a KeyError into a log nobody reads.
    Saying so and taking the buttons off makes the dead button go away.
    """
    query = update.callback_query
    if query is None:
        await update.effective_message.reply_text(DRAFT_GONE)
        return ConversationHandler.END

    message_id = query.message.message_id if query.message is not None else None
    if message_id is not None and message_id in context.user_data.get(SAVED_BUTTONS_KEY, []):
        # This preview was saved and already says so. A late press must not claim the
        # draft was lost, and must not write anything a second time.
        await query.answer(ALREADY_SAVED)
        return ConversationHandler.END

    await query.answer(DRAFT_GONE)
    try:
        await query.edit_message_text(DRAFT_GONE, reply_markup=None)
    except Exception:
        logger.warning("Could not take the buttons off a stale preview", exc_info=True)
    return ConversationHandler.END


def _preview_keyboard(highlighted: bool = False) -> InlineKeyboardMarkup:
    highlight_btn = (
        InlineKeyboardButton("⭐ Highlighted", callback_data="toggle_highlight")
        if highlighted else
        InlineKeyboardButton("Mark as Highlight ⭐", callback_data="toggle_highlight")
    )
    return InlineKeyboardMarkup([
        [
            InlineKeyboardButton("✎ Title", callback_data="edit_title"),
            InlineKeyboardButton("✎ Text", callback_data="edit_text"),
            InlineKeyboardButton("✎ Tags", callback_data="edit_tags"),
        ],
        [highlight_btn],
        [InlineKeyboardButton("✓ Save", callback_data="save")],
        # Its own row, under Save rather than beside it. Discarding is the one
        # irreversible thing in this keyboard — the transcription and the
        # formatting have already been paid for and the messages are deleted —
        # so it does not sit a thumb's width from the button pressed every time.
        [InlineKeyboardButton("✕ Cancel", callback_data="cancel")],
    ])


async def handle_start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    await update.effective_message.reply_text(WELCOME_TEXT)


async def handle_help(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    await reply_html(update.effective_message, HELP_TEXT)


def _discard_temp_file(path: str | None) -> None:
    """Removes a downloaded audio file, if there is one.

    Never raises. This runs on the failure path too, and a temp file we cannot delete
    must not replace the error we are already reporting.
    """
    if path is None:
        return
    try:
        os.unlink(path)
    except OSError:
        logger.warning("Could not remove temporary audio file %s", path, exc_info=True)


async def handle_voice(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    message = update.effective_message

    # A recording sent while a preview is still open replaces it — but only once the
    # replacement exists. Everything below can fail, and a draft the user has not saved
    # yet must not be thrown away for a recording that never arrives: the old preview
    # stays live and the failed recording is the one that is lost. Which means failing
    # has to leave the conversation exactly where it found it — including mid-edit,
    # where the preview's keyboard is off and the prompt the user can still answer is
    # the only way back.
    if context.user_data.get("pending") is None:
        on_failure = ConversationHandler.END
    else:
        on_failure = context.user_data.get("editing_state", PREVIEW)

    await message.reply_text("Listening...")

    # The download lives inside the guarded region: get_file and download_to_drive can
    # both fail — a network blip, or a voice note too large for the Bot API — and the
    # file has already been created by then.
    tmp_path = None
    try:
        try:
            voice_file = await context.bot.get_file(message.voice.file_id)
            with tempfile.NamedTemporaryFile(suffix=".ogg", delete=False) as tmp:
                tmp_path = tmp.name
            await voice_file.download_to_drive(tmp_path)
        except Exception:
            logger.exception("Error downloading voice message")
            await message.reply_text(DOWNLOAD_FAILED)
            return on_failure

        try:
            await message.reply_text("Transcribing...")
            transcription = await transcribe(tmp_path)
        except Exception:
            logger.exception("Error transcribing voice message")
            await message.reply_text(TRANSCRIBE_FAILED)
            return on_failure
    finally:
        _discard_temp_file(tmp_path)

    logger.info("Transcription: %s", transcription)

    try:
        await message.reply_text("Formatting...")
        title, text, tags = await format_entry(transcription)
    except Exception:
        logger.exception("Error formatting transcription")
        await message.reply_text(FORMAT_FAILED)
        return on_failure

    try:
        title_msg = await reply_html(message, _title_body(title))
        text_msg = await message.reply_text(text)
        tags_msg = await reply_html(message, _tags_line(tags))
        buttons_msg = await message.reply_text("Actions:", reply_markup=_preview_keyboard(highlighted=False))
    except Exception:
        logger.exception("Error sending the preview")
        await message.reply_text(PREVIEW_FAILED)
        return on_failure

    # The new preview is up, so the old one can go. Its message ids live under the same
    # keys that are about to be overwritten, so its buttons have to come off here or
    # they would end up driving the new draft. The editing prompt goes too: a "send a
    # new title" that belonged to the replaced draft answers to nothing now.
    previous = _clear_draft(context)
    if previous.get("pending") is not None:
        chat_id = update.effective_chat.id
        await _retire_preview(context.bot, chat_id, previous, DRAFT_REPLACED)
        await _delete_messages(context.bot, chat_id, [previous["edit_prompt_msg_id"]])

    context.user_data["pending"] = {"title": title, "text": text, "tags": tags}
    context.user_data["title_msg_id"] = title_msg.message_id
    context.user_data["text_msg_id"] = text_msg.message_id
    context.user_data["tags_msg_id"] = tags_msg.message_id
    context.user_data["buttons_msg_id"] = buttons_msg.message_id

    return PREVIEW


async def save_callback(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    pending = context.user_data.get("pending")
    if pending is None:
        return await _draft_missing(update, context)

    query = update.callback_query

    # Read and set with no await in between, so two presses cannot both get past here
    # whatever the application's update concurrency is set to.
    if context.user_data.get("saving"):
        await query.answer(SAVE_IN_FLIGHT)
        return PREVIEW
    context.user_data["saving"] = True

    await query.answer()

    # The keyboard comes off before the round trip, not after it returns. Saving is two
    # HTTP requests when today's page already exists, and Telegram leaves a button live
    # until the message is edited.
    try:
        await query.edit_message_text(SAVING_NOTICE, reply_markup=None)
    except Exception:
        logger.warning("Could not take the buttons off the preview before saving", exc_info=True)

    try:
        updated = await save_entry(pending["title"], pending["text"], pending["tags"])
    except Exception:
        logger.exception("Error saving to Notion")
        # A genuine failure keeps the draft and puts the keyboard back, so Save can be
        # pressed again rather than the whole note having to be dictated again.
        context.user_data["saving"] = False
        try:
            await query.edit_message_text(
                NOTION_FAILED,
                reply_markup=_preview_keyboard(highlighted=pending["title"].startswith("⭐ ")),
            )
        except Exception:
            logger.warning("Could not restore the preview keyboard after a failed save", exc_info=True)
        return PREVIEW

    status = "Added to today's page" if updated else "Saved to Notion"
    _remember_saved(context, context.user_data.get("buttons_msg_id"))
    _clear_draft(context)
    await query.edit_message_text(f"✓ {status}", reply_markup=None)
    return ConversationHandler.END


async def toggle_highlight_callback(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    pending = context.user_data.get("pending")
    if pending is None:
        return await _draft_missing(update, context)

    query = update.callback_query
    await query.answer()

    highlighted = pending["title"].startswith("⭐ ")
    if highlighted:
        pending["title"] = pending["title"][len("⭐ "):]
    else:
        pending["title"] = f"⭐ {pending['title']}"

    highlighted = not highlighted
    chat_id = update.effective_chat.id
    await edit_html(
        context.bot,
        chat_id,
        context.user_data["title_msg_id"],
        _title_body(pending["title"]),
    )
    await context.bot.edit_message_reply_markup(
        chat_id=chat_id,
        message_id=context.user_data["buttons_msg_id"],
        reply_markup=_preview_keyboard(highlighted=highlighted),
    )
    return PREVIEW


async def edit_title_callback(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    if context.user_data.get("pending") is None:
        return await _draft_missing(update, context)

    query = update.callback_query
    await query.answer()
    await query.edit_message_reply_markup(reply_markup=None)
    prompt = await query.message.reply_text("Send a new title:")
    context.user_data["edit_prompt_msg_id"] = prompt.message_id
    context.user_data["editing_state"] = EDIT_TITLE
    return EDIT_TITLE


async def edit_text_callback(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    if context.user_data.get("pending") is None:
        return await _draft_missing(update, context)

    query = update.callback_query
    await query.answer()
    await query.edit_message_reply_markup(reply_markup=None)
    prompt = await query.message.reply_text("Send a new text:")
    context.user_data["edit_prompt_msg_id"] = prompt.message_id
    context.user_data["editing_state"] = EDIT_TEXT
    return EDIT_TEXT


async def receive_new_title(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    if context.user_data.get("pending") is None:
        return await _draft_missing(update, context)

    user_msg = update.effective_message
    context.user_data["pending"]["title"] = user_msg.text.strip()

    chat_id = update.effective_chat.id
    await edit_html(
        context.bot,
        chat_id,
        context.user_data["title_msg_id"],
        _title_body(context.user_data["pending"]["title"]),
    )
    await context.bot.edit_message_reply_markup(
        chat_id=chat_id,
        message_id=context.user_data["buttons_msg_id"],
        reply_markup=_preview_keyboard(highlighted=context.user_data["pending"]["title"].startswith("⭐ ")),
    )
    # Popped, so /cancel does not later try to delete a prompt that is already gone,
    # and so an interrupted recording is not sent back to an edit that is finished.
    context.user_data.pop("editing_state", None)
    await _delete_messages(context.bot, chat_id, [
        context.user_data.pop("edit_prompt_msg_id", None),
        user_msg.message_id,
    ])
    return PREVIEW


async def receive_new_text(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    if context.user_data.get("pending") is None:
        return await _draft_missing(update, context)

    user_msg = update.effective_message
    context.user_data["pending"]["text"] = user_msg.text.strip()

    chat_id = update.effective_chat.id
    await context.bot.edit_message_text(
        chat_id=chat_id,
        message_id=context.user_data["text_msg_id"],
        text=context.user_data["pending"]["text"],
    )
    await context.bot.edit_message_reply_markup(
        chat_id=chat_id,
        message_id=context.user_data["buttons_msg_id"],
        reply_markup=_preview_keyboard(highlighted=context.user_data["pending"]["title"].startswith("⭐ ")),
    )
    # Popped, so /cancel does not later try to delete a prompt that is already gone,
    # and so an interrupted recording is not sent back to an edit that is finished.
    context.user_data.pop("editing_state", None)
    await _delete_messages(context.bot, chat_id, [
        context.user_data.pop("edit_prompt_msg_id", None),
        user_msg.message_id,
    ])
    return PREVIEW


async def edit_tags_callback(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    if context.user_data.get("pending") is None:
        return await _draft_missing(update, context)

    query = update.callback_query
    await query.answer()
    await query.edit_message_reply_markup(reply_markup=None)
    prompt = await query.message.reply_text("Send tags separated by commas:")
    context.user_data["edit_prompt_msg_id"] = prompt.message_id
    context.user_data["editing_state"] = EDIT_TAGS
    return EDIT_TAGS


async def receive_new_tags(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    if context.user_data.get("pending") is None:
        return await _draft_missing(update, context)

    user_msg = update.effective_message
    new_tags = [t.strip() for t in user_msg.text.split(",") if t.strip()]
    context.user_data["pending"]["tags"] = new_tags

    chat_id = update.effective_chat.id
    await edit_html(
        context.bot,
        chat_id,
        context.user_data["tags_msg_id"],
        _tags_line(new_tags),
    )
    await context.bot.edit_message_reply_markup(
        chat_id=chat_id,
        message_id=context.user_data["buttons_msg_id"],
        reply_markup=_preview_keyboard(highlighted=context.user_data["pending"]["title"].startswith("⭐ ")),
    )
    # Popped, so /cancel does not later try to delete a prompt that is already gone,
    # and so an interrupted recording is not sent back to an edit that is finished.
    context.user_data.pop("editing_state", None)
    await _delete_messages(context.bot, chat_id, [
        context.user_data.pop("edit_prompt_msg_id", None),
        user_msg.message_id,
    ])
    return PREVIEW


async def _discard_draft(context: ContextTypes.DEFAULT_TYPE, chat_id: int, draft: dict) -> bool:
    """Takes a cleared draft off the screen. True if the preview said so itself."""
    await _delete_messages(context.bot, chat_id, [
        draft["title_msg_id"],
        draft["text_msg_id"],
        draft["tags_msg_id"],
        draft["edit_prompt_msg_id"],
    ])
    return await _retire_preview(context.bot, chat_id, draft, DRAFT_CANCELLED)


async def handle_cancel(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    draft = _clear_draft(context)
    if draft.get("pending") is None:
        await update.effective_message.reply_text(NOTHING_TO_CANCEL)
        return ConversationHandler.END

    chat_id = update.effective_chat.id
    if not await _discard_draft(context, chat_id, draft):
        await update.effective_message.reply_text(DRAFT_CANCELLED)
    return ConversationHandler.END


async def cancel_callback(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    """The ✕ Cancel button. Same outcome as /cancel, reached without typing.

    /cancel stays: it is the way out when the preview has scrolled away, and it
    is the conversation's fallback, which a callback cannot be.
    """
    if context.user_data.get("pending") is None:
        return await _draft_missing(update, context)

    await update.callback_query.answer()
    draft = _clear_draft(context)
    await _discard_draft(context, update.effective_chat.id, draft)
    return ConversationHandler.END


async def handle_preview_timeout(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    draft = _clear_draft(context)
    if draft.get("pending") is None:
        return ConversationHandler.END

    logger.info("Preview timed out, discarding draft")
    await _retire_preview(context.bot, update.effective_chat.id, draft, DRAFT_TIMED_OUT)
    return ConversationHandler.END


async def handle_weekly(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    await update.effective_message.reply_text("Generating weekly report...")
    try:
        report = await generate_weekly_report()
        if report:
            await reply_html(
                update.effective_message,
                render(WEEKLY_REPORT_TEMPLATE, report=report),
            )
        else:
            await update.effective_message.reply_text("No entries this week.")
    except Exception:
        logger.exception("Error generating weekly report")
        await update.effective_message.reply_text("Error generating weekly report.")


async def send_weekly_report(context: ContextTypes.DEFAULT_TYPE) -> None:
    logger.info("Generating weekly report...")
    try:
        report = await generate_weekly_report()
        if report:
            await send_html(
                context.bot,
                settings.allowed_user_id,
                render(WEEKLY_REPORT_TEMPLATE, report=report),
            )
        else:
            await context.bot.send_message(
                chat_id=settings.allowed_user_id,
                text="No entries this week — next week is a fresh start!",
            )
    except Exception:
        logger.exception("Error generating weekly report")


async def send_daily_summary(context: ContextTypes.DEFAULT_TYPE) -> None:
    logger.info("Generating daily summary...")
    try:
        summary = await generate_daily_summary()
        if summary:
            await send_html(
                context.bot,
                settings.allowed_user_id,
                render(DAILY_SUMMARY_TEMPLATE, summary=summary),
            )
        else:
            await context.bot.send_message(
                chat_id=settings.allowed_user_id,
                text="Hey, how was your day? I'm sure you have something to be proud of!",
            )
    except Exception:
        logger.exception("Error generating daily summary")


async def handle_error(update: object, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Last line of defence: log the traceback, tell the user something happened.

    Whatever went wrong stays in the log. The user gets one fixed sentence, so a
    third-party response body can never reach the chat by this route.
    """
    logger.error("Unhandled exception while processing an update", exc_info=context.error)

    if not isinstance(update, Update):
        return

    if update.callback_query is not None:
        # One failure, one notification. `effective_message` for a callback update is
        # the message the button sits on, so falling through to the reply below would
        # tell the user twice — once as a toast and once in the chat.
        try:
            await update.callback_query.answer(SOMETHING_BROKE)
        except Exception:
            logger.warning("Could not answer the callback query after an error", exc_info=True)
        return

    message = update.effective_message
    if message is not None:
        try:
            await message.reply_text(SOMETHING_BROKE)
        except Exception:
            logger.warning("Could not tell the user about the error", exc_info=True)


def state_file_path() -> str:
    """Where the draft pickle goes.

    systemd exports STATE_DIRECTORY for a unit that declares StateDirectory=, and under
    the deployment's ProtectSystem=strict that directory is the only one the bot may
    write to -- the working directory is read-only. A relative path would not stop the
    bot if it failed: a persistence error is reported with no update attached, so it is
    logged and swallowed, and the draft silently never gets written. The current
    directory is the fallback for running outside systemd.
    """
    return os.path.join(os.environ.get("STATE_DIRECTORY", "."), STATE_FILE_NAME)


def build_application() -> Application:
    app = (
        ApplicationBuilder()
        .token(settings.telegram_token)
        .persistence(PicklePersistence(filepath=state_file_path()))
        .build()
    )

    user_filter = filters.User(user_id=settings.allowed_user_id)

    command_handlers = [
        CommandHandler("start", handle_start),
        CommandHandler("help", handle_help),
        CommandHandler("weekly", handle_weekly),
    ]
    cancel_handler = CommandHandler("cancel", handle_cancel)

    conv_handler = ConversationHandler(
        entry_points=[MessageHandler(filters.VOICE & user_filter, handle_voice)],
        states={
            PREVIEW: [
                CallbackQueryHandler(save_callback, pattern="^save$"),
                CallbackQueryHandler(toggle_highlight_callback, pattern="^toggle_highlight$"),
                CallbackQueryHandler(edit_title_callback, pattern="^edit_title$"),
                CallbackQueryHandler(edit_text_callback, pattern="^edit_text$"),
                CallbackQueryHandler(edit_tags_callback, pattern="^edit_tags$"),
                CallbackQueryHandler(cancel_callback, pattern="^cancel$"),
                *command_handlers,
            ],
            EDIT_TITLE: [MessageHandler(filters.TEXT & ~filters.COMMAND & user_filter, receive_new_title), *command_handlers],
            EDIT_TEXT: [MessageHandler(filters.TEXT & ~filters.COMMAND & user_filter, receive_new_text), *command_handlers],
            EDIT_TAGS: [MessageHandler(filters.TEXT & ~filters.COMMAND & user_filter, receive_new_tags), *command_handlers],
            ConversationHandler.TIMEOUT: [TypeHandler(Update, handle_preview_timeout)],
        },
        fallbacks=[cancel_handler],
        # With allow_reentry the entry points are checked in every state, not only when
        # no conversation is running, so a new voice message is picked up from PREVIEW
        # and from all three editing states. A VOICE handler added to PREVIEW alone
        # would still swallow a recording sent while the bot waits for a new title.
        allow_reentry=True,
        conversation_timeout=PREVIEW_TIMEOUT,
        name=CONVERSATION_NAME,
        persistent=True,
    )

    app.add_handler(conv_handler)
    for handler in [*command_handlers, cancel_handler]:
        app.add_handler(handler)

    # Reached only when the conversation did not take the callback — a preview left in
    # the chat by an older process, or one whose conversation has already ended. Only
    # one handler per group runs, and the conversation is registered first, so this
    # never steals a callback from a live draft.
    app.add_handler(CallbackQueryHandler(
        _draft_missing,
        pattern="^(save|toggle_highlight|edit_title|edit_text|edit_tags|cancel)$",
    ))

    app.add_error_handler(handle_error)

    tz = zoneinfo.ZoneInfo(settings.timezone)
    app.job_queue.run_daily(
        send_daily_summary,
        time=time(21, 0, tzinfo=tz),
        name=DAILY_SUMMARY_JOB,
    )
    app.job_queue.run_daily(
        send_weekly_report,
        time=time(21, 0, tzinfo=tz),
        days=(SUNDAY,),
        name=WEEKLY_REPORT_JOB,
    )

    return app


def main() -> None:
    app = build_application()
    logger.info("Bot started")
    app.run_polling()


if __name__ == "__main__":
    main()
